import type { ScanReport, Clause } from '../types/report';

const loadJsPdf = () => import('jspdf');

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const MARGIN = 20;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const FOOTER_Y = 285;

const COLORS = {
  brand: [37, 99, 235] as [number, number, number],
  cyan: [6, 182, 212] as [number, number, number],
  green: [34, 197, 94] as [number, number, number],
  red: [239, 68, 68] as [number, number, number],
  yellow: [234, 179, 8] as [number, number, number],
  slate700: [51, 65, 85] as [number, number, number],
  slate400: [148, 163, 184] as [number, number, number],
  slate300: [203, 213, 225] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  black: [0, 0, 0] as [number, number, number],
  darkBg: [15, 23, 42] as [number, number, number],
};

function getScoreColor(score: number): [number, number, number] {
  if (score >= 80) return COLORS.green;
  if (score >= 50) return COLORS.yellow;
  return COLORS.red;
}

function getStatusColor(status: Clause['status']): [number, number, number] {
  switch (status) {
    case 'pass': return COLORS.green;
    case 'fail': return COLORS.red;
    case 'needs_review': return COLORS.yellow;
    default: return COLORS.slate400;
  }
}

function getStatusLabel(status: Clause['status']): string {
  switch (status) {
    case 'pass': return 'PASS';
    case 'fail': return 'FAIL';
    case 'needs_review': return 'REVIEW';
    default: return 'N/A';
  }
}

export async function exportPdf(report: ScanReport) {
  const { jsPDF } = await loadJsPdf();
  const pdf = new jsPDF('p', 'mm', 'a4');
  let pageNum = 0;

  const score = report.summary.totalChecks > 0
    ? Math.round((report.summary.passed / report.summary.totalChecks) * 100)
    : 0;

  const scannedDate = new Date(report.scannedAt).toLocaleDateString('en-GB', {
    year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit',
  });

  function addFooter() {
    pageNum++;
    pdf.setFontSize(7);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(...COLORS.slate400);
    pdf.text('Generated by EAA Stream Checker', MARGIN, FOOTER_Y);
    pdf.text(`Page ${pageNum}`, PAGE_WIDTH - MARGIN, FOOTER_Y, { align: 'right' });
  }

  function newPage() {
    pdf.addPage();
    addFooter();
  }

  let y = MARGIN;
  function checkPage(needed: number) {
    if (y + needed > FOOTER_Y - 5) {
      newPage();
      y = MARGIN;
    }
  }

  // ─── COVER PAGE ───────────────────────────────────────────────
  // Background
  pdf.setFillColor(...COLORS.darkBg);
  pdf.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');

  // Brand accent line
  pdf.setFillColor(...COLORS.brand);
  pdf.rect(MARGIN, 40, 60, 1.5, 'F');

  // Title
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(32);
  pdf.setTextColor(...COLORS.white);
  pdf.text('EAA Compliance', MARGIN, 58);
  pdf.text('Report', MARGIN, 70);

  // Subtitle
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(...COLORS.slate400);
  pdf.text('EN 301 549 Compliance Assessment', MARGIN, 82);
  pdf.text('European Accessibility Act', MARGIN, 88);

  // Score circle on cover
  const scoreColor = getScoreColor(score);
  const cx = PAGE_WIDTH - MARGIN - 25;
  const cy = 65;
  const radius = 22;

  // Circle background
  pdf.setDrawColor(...COLORS.slate700);
  pdf.setLineWidth(2.5);
  pdf.circle(cx, cy, radius, 'S');

  // Score arc (simplified as a colored circle border)
  pdf.setDrawColor(...scoreColor);
  pdf.setLineWidth(2.5);
  // Draw partial arc based on score — simplified as full circle with color
  pdf.circle(cx, cy, radius, 'S');

  // Score text
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(24);
  pdf.setTextColor(...scoreColor);
  pdf.text(`${score}`, cx, cy + 2, { align: 'center' });
  pdf.setFontSize(8);
  pdf.setTextColor(...COLORS.slate400);
  pdf.text('/ 100', cx, cy + 8, { align: 'center' });

  // Details box
  const boxY = 110;
  pdf.setFillColor(30, 41, 59);
  pdf.roundedRect(MARGIN, boxY, CONTENT_WIDTH, 52, 3, 3, 'F');

  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(...COLORS.slate300);
  const details = [
    ['URL', report.url],
    ['Date', scannedDate],
    ['Report ID', report.id],
    ['Total Checks', `${report.summary.totalChecks}`],
    ['Passed / Failed / Review', `${report.summary.passed} / ${report.summary.failed} / ${report.summary.needsReview}`],
  ];
  let detailY = boxY + 10;
  for (const [label, value] of details) {
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...COLORS.slate400);
    pdf.text(label, MARGIN + 8, detailY);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(...COLORS.white);
    const valueLines = pdf.splitTextToSize(value, CONTENT_WIDTH - 50);
    pdf.text(valueLines[0], MARGIN + 50, detailY);
    detailY += 8;
  }

  // Deep scan badge
  if (report.deepScan && report.pagesScanned) {
    detailY += 4;
    pdf.setFontSize(8);
    pdf.setTextColor(...COLORS.cyan);
    pdf.text(`Deep Scan — ${report.pagesScanned.length} pages analyzed`, MARGIN + 8, detailY);
  }

  // Footer text
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(...COLORS.slate400);
  pdf.text('EAA Stream Checker', MARGIN, PAGE_HEIGHT - 20);
  addFooter();

  // ─── EXECUTIVE SUMMARY PAGE ─────────────────────────────────────
  newPage();
  y = MARGIN;

  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(...COLORS.black);
  pdf.text('Executive Summary', MARGIN, y);
  y += 12;

  // Summary stats as colored boxes
  const statBoxWidth = (CONTENT_WIDTH - 6) / 3;
  const stats = [
    { label: 'Passed', value: report.summary.passed, color: COLORS.green },
    { label: 'Failed', value: report.summary.failed, color: COLORS.red },
    { label: 'Needs Review', value: report.summary.needsReview, color: COLORS.yellow },
  ];

  for (let i = 0; i < stats.length; i++) {
    const sx = MARGIN + i * (statBoxWidth + 3);
    pdf.setFillColor(245, 247, 250);
    pdf.roundedRect(sx, y, statBoxWidth, 18, 2, 2, 'F');
    // Color accent bar
    pdf.setFillColor(...stats[i].color);
    pdf.rect(sx, y, statBoxWidth, 2, 'F');
    // Value
    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...stats[i].color);
    pdf.text(`${stats[i].value}`, sx + statBoxWidth / 2, y + 11, { align: 'center' });
    // Label
    pdf.setFontSize(7);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(100, 116, 139);
    pdf.text(stats[i].label, sx + statBoxWidth / 2, y + 16, { align: 'center' });
  }
  y += 26;

  // Pages scanned (if deep scan)
  if (report.deepScan && report.pagesScanned && report.pagesScanned.length > 1) {
    checkPage(10 + report.pagesScanned.length * 5);
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...COLORS.black);
    pdf.text('Pages Scanned', MARGIN, y);
    y += 6;

    for (const page of report.pagesScanned) {
      checkPage(5);
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(71, 85, 105);
      const pageUrl = pdf.splitTextToSize(page.url, CONTENT_WIDTH - 40);
      pdf.text(pageUrl[0], MARGIN + 4, y);
      pdf.setTextColor(page.violationCount > 0 ? 239 : 34, page.violationCount > 0 ? 68 : 197, page.violationCount > 0 ? 68 : 94);
      pdf.text(`${page.violationCount} violations`, MARGIN + CONTENT_WIDTH - 25, y, { align: 'right' });
      y += 5;
    }
    y += 6;
  }

  // ─── CLAUSE DETAIL SECTIONS ───────────────────────────────────
  const videoClauses = report.clauses.filter((c) => c.category === 'video');
  const webClauses = report.clauses.filter((c) => c.category === 'web_content');

  const sections = [
    ...(videoClauses.length > 0
      ? [{ heading: 'Clause 7 — Video & Streaming', clauses: videoClauses, accentColor: [139, 92, 246] as [number, number, number] }]
      : []),
    ...(webClauses.length > 0
      ? [{ heading: 'Clause 9 — Web Content (WCAG 2.1 AA)', clauses: webClauses, accentColor: COLORS.cyan }]
      : []),
  ];

  for (const section of sections) {
    checkPage(16);

    // Section header with colored bar
    pdf.setFillColor(...section.accentColor);
    pdf.rect(MARGIN, y, CONTENT_WIDTH, 1, 'F');
    y += 5;

    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...COLORS.black);
    pdf.text(section.heading, MARGIN, y);
    y += 10;

    for (const clause of section.clauses) {
      checkPage(14);

      // Status badge + clause header
      const statusColor = getStatusColor(clause.status);
      const statusLabel = getStatusLabel(clause.status);

      // Status pill
      pdf.setFillColor(...statusColor);
      pdf.roundedRect(MARGIN, y - 3.5, 14, 5, 1.5, 1.5, 'F');
      pdf.setFontSize(6);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(255, 255, 255);
      pdf.text(statusLabel, MARGIN + 7, y, { align: 'center' });

      // Clause ID + title
      pdf.setFontSize(9);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(30, 41, 59);
      pdf.text(clause.clauseId, MARGIN + 18, y);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(71, 85, 105);
      const titleText = pdf.splitTextToSize(`— ${clause.title}`, CONTENT_WIDTH - 40);
      pdf.text(titleText[0], MARGIN + 28, y);
      y += 6;

      // Findings
      for (const finding of clause.findings) {
        checkPage(10);
        pdf.setFontSize(8);

        // Severity
        const sevColor = finding.severity === 'critical' ? COLORS.red : finding.severity === 'major' ? [249, 115, 22] as [number, number, number] : COLORS.brand;
        pdf.setFont('helvetica', 'bold');
        pdf.setTextColor(...sevColor);
        pdf.text(`[${finding.severity.toUpperCase()}]`, MARGIN + 4, y);

        // Description
        pdf.setFont('helvetica', 'normal');
        pdf.setTextColor(71, 85, 105);
        const descLines = pdf.splitTextToSize(finding.description, CONTENT_WIDTH - 24);
        for (const line of descLines) {
          checkPage(4);
          pdf.text(line, MARGIN + 22, y);
          y += 4;
        }

        // Evidence
        if (finding.evidence) {
          checkPage(5);
          pdf.setFillColor(248, 250, 252);
          const evidenceLines = pdf.splitTextToSize(finding.evidence, CONTENT_WIDTH - 16);
          const evidenceSlice = evidenceLines.slice(0, 4);
          const evidenceHeight = evidenceSlice.length * 3.5 + 4;
          pdf.roundedRect(MARGIN + 6, y - 2, CONTENT_WIDTH - 12, evidenceHeight, 1, 1, 'F');
          pdf.setFontSize(6.5);
          pdf.setTextColor(100, 116, 139);
          for (const el of evidenceSlice) {
            checkPage(3.5);
            pdf.text(el, MARGIN + 10, y + 1);
            y += 3.5;
          }
          y += 2;
        }
        y += 1;
      }

      // Recommendation
      if (clause.recommendation) {
        checkPage(10);
        pdf.setFillColor(239, 246, 255);
        const recLines = pdf.splitTextToSize(`Recommendation: ${clause.recommendation}`, CONTENT_WIDTH - 16);
        const recHeight = recLines.length * 4 + 4;
        pdf.roundedRect(MARGIN + 4, y - 2, CONTENT_WIDTH - 8, recHeight, 1.5, 1.5, 'F');
        pdf.setFontSize(8);
        pdf.setFont('helvetica', 'italic');
        pdf.setTextColor(37, 99, 235);
        for (const rl of recLines) {
          checkPage(4);
          pdf.text(rl, MARGIN + 8, y + 1);
          y += 4;
        }
        y += 2;
      }

      y += 3;
    }
  }

  pdf.save(`eaa-report-${report.id}.pdf`);
}
