import type { ScanReport, Clause } from '../types/report';

const loadJsPdf = () => import('jspdf');

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const MARGIN = 20;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const FOOTER_Y = 285;

const COLORS = {
  brand: [37, 99, 235] as [number, number, number],
  green: [34, 197, 94] as [number, number, number],
  red: [239, 68, 68] as [number, number, number],
  yellow: [234, 179, 8] as [number, number, number],
  slate700: [51, 65, 85] as [number, number, number],
  slate500: [100, 116, 139] as [number, number, number],
  slate400: [148, 163, 184] as [number, number, number],
  slate300: [203, 213, 225] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  black: [0, 0, 0] as [number, number, number],
  darkBg: [15, 23, 42] as [number, number, number],
  headerBg: [241, 245, 249] as [number, number, number],
  rowAlt: [248, 250, 252] as [number, number, number],
};

/**
 * Map our internal status to VPAT 2.5 conformance levels.
 */
function toConformanceLevel(status: Clause['status']): string {
  switch (status) {
    case 'pass': return 'Supports';
    case 'fail': return 'Does Not Support';
    case 'needs_review': return 'Partially Supports';
    case 'not_applicable': return 'Not Applicable';
    default: return 'Not Evaluated';
  }
}

function conformanceColor(status: Clause['status']): [number, number, number] {
  switch (status) {
    case 'pass': return COLORS.green;
    case 'fail': return COLORS.red;
    case 'needs_review': return COLORS.yellow;
    default: return COLORS.slate400;
  }
}

function buildRemarks(clause: Clause): string {
  if (clause.status === 'pass') return 'All automated checks passed.';
  if (clause.status === 'not_applicable') return 'Not applicable to this product.';

  const remarks = clause.findings.map((f) => f.description).filter(Boolean);
  if (remarks.length === 0) return 'Requires manual verification.';
  // Limit to 2 remarks to keep the table readable
  const limited = remarks.slice(0, 2);
  if (remarks.length > 2) limited.push(`+ ${remarks.length - 2} more issues`);
  return limited.join('; ');
}

/**
 * Export a VPAT 2.5 EU Edition (EN 301 549) PDF pre-filled with scan results.
 */
export async function exportVpat(report: ScanReport) {
  const { jsPDF } = await loadJsPdf();
  const pdf = new jsPDF('p', 'mm', 'a4');
  let pageNum = 0;

  const scannedDate = new Date(report.scannedAt).toLocaleDateString('en-GB', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  function addFooter() {
    pageNum++;
    pdf.setFontSize(7);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(...COLORS.slate400);
    pdf.text('VPAT 2.5 EU Edition — Generated by EAA Stream Checker', MARGIN, FOOTER_Y);
    pdf.text(`Page ${pageNum}`, PAGE_WIDTH - MARGIN, FOOTER_Y, { align: 'right' });
  }

  function newPage() {
    pdf.addPage();
    addFooter();
    return MARGIN;
  }

  let y = MARGIN;
  function checkPage(needed: number): void {
    if (y + needed > FOOTER_Y - 5) {
      y = newPage();
    }
  }

  // ─── COVER PAGE ───────────────────────────────────────────────
  pdf.setFillColor(...COLORS.darkBg);
  pdf.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');

  // Accent line
  pdf.setFillColor(...COLORS.brand);
  pdf.rect(MARGIN, 40, 60, 1.5, 'F');

  // Title
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(28);
  pdf.setTextColor(...COLORS.white);
  pdf.text('Accessibility', MARGIN, 56);
  pdf.text('Conformance Report', MARGIN, 68);

  // Subtitle
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(...COLORS.slate400);
  pdf.text('VPAT\u00AE 2.5 — EU Edition (EN 301 549)', MARGIN, 80);

  // Product info box
  const boxY = 100;
  pdf.setFillColor(30, 41, 59);
  pdf.roundedRect(MARGIN, boxY, CONTENT_WIDTH, 62, 3, 3, 'F');

  const fields = [
    ['Product Name', new URL(report.url).hostname],
    ['Product URL', report.url],
    ['Report Date', scannedDate],
    ['Report ID', report.id],
    ['Standard', 'EN 301 549 V3.2.1 (2021-03)'],
    ['Assessment Method', 'Automated scan (axe-core + streaming analysis)'],
  ];

  let fieldY = boxY + 10;
  for (const [label, value] of fields) {
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...COLORS.slate400);
    pdf.text(label, MARGIN + 8, fieldY);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(...COLORS.white);
    const lines = pdf.splitTextToSize(value, CONTENT_WIDTH - 60);
    pdf.text(lines[0], MARGIN + 55, fieldY);
    fieldY += 9;
  }

  // Disclaimer
  pdf.setFontSize(7);
  pdf.setTextColor(...COLORS.slate500);
  const disclaimer = 'This report is based on automated testing and may not cover all accessibility requirements. Manual testing by accessibility experts is recommended to supplement these findings. The VPAT\u00AE template is a registered trademark of the Information Technology Industry Council (ITI).';
  const disclaimerLines = pdf.splitTextToSize(disclaimer, CONTENT_WIDTH - 16);
  pdf.text(disclaimerLines, MARGIN + 8, 185);

  pdf.setFontSize(8);
  pdf.setTextColor(...COLORS.slate400);
  pdf.text('EAA Stream Checker', MARGIN, PAGE_HEIGHT - 20);
  addFooter();

  // ─── TABLE OF CONTENTS / SUMMARY ──────────────────────────────
  y = newPage();

  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(...COLORS.black);
  pdf.text('Conformance Summary', MARGIN, y);
  y += 10;

  // Summary stats
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(...COLORS.slate700);
  const totalClauses = report.clauses.length;
  const supports = report.clauses.filter(c => c.status === 'pass').length;
  const doesNotSupport = report.clauses.filter(c => c.status === 'fail').length;
  const partiallySupports = report.clauses.filter(c => c.status === 'needs_review').length;
  const notApplicable = report.clauses.filter(c => c.status === 'not_applicable').length;

  const summaryRows = [
    ['Supports', `${supports}`, COLORS.green],
    ['Partially Supports', `${partiallySupports}`, COLORS.yellow],
    ['Does Not Support', `${doesNotSupport}`, COLORS.red],
    ['Not Applicable', `${notApplicable}`, COLORS.slate400],
    ['Total Criteria Evaluated', `${totalClauses}`, COLORS.slate700],
  ] as [string, string, [number, number, number]][];

  for (const [label, count, color] of summaryRows) {
    checkPage(7);
    pdf.setFillColor(...color);
    pdf.circle(MARGIN + 3, y - 1, 1.5, 'F');
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(...COLORS.slate700);
    pdf.text(label, MARGIN + 8, y);
    pdf.setFont('helvetica', 'bold');
    pdf.text(count, MARGIN + CONTENT_WIDTH - 5, y, { align: 'right' });
    y += 7;
  }

  y += 8;

  // Notes
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(...COLORS.black);
  pdf.text('Notes', MARGIN, y);
  y += 5;
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(...COLORS.slate700);
  pdf.setFontSize(8);
  const notes = [
    'This VPAT covers EN 301 549 Clause 7 (Video & Streaming) and Clause 9 (Web Content / WCAG 2.2 AA).',
    'Conformance levels are based on automated testing. "Partially Supports" indicates items requiring manual review.',
    'This report should be supplemented with manual accessibility testing for complete coverage.',
    `Assessment was performed on ${scannedDate}.${report.deepScan ? ` Deep scan covered ${report.pagesScanned?.length ?? 1} pages.` : ''}`,
  ];
  for (const note of notes) {
    checkPage(5);
    pdf.text(`\u2022  ${note}`, MARGIN + 2, y, { maxWidth: CONTENT_WIDTH - 4 });
    y += pdf.splitTextToSize(`\u2022  ${note}`, CONTENT_WIDTH - 4).length * 3.5 + 2;
  }

  // ─── CLAUSE 7 TABLE ────────────────────────────────────────────
  const videoClauses = report.clauses.filter(c => c.category === 'video');
  const webClauses = report.clauses.filter(c => c.category === 'web_content');

  function renderTable(
    heading: string,
    subheading: string,
    clauses: Clause[],
    accentColor: [number, number, number],
  ) {
    y += 6;
    checkPage(20);

    // Section header
    pdf.setFillColor(...accentColor);
    pdf.rect(MARGIN, y, CONTENT_WIDTH, 1, 'F');
    y += 5;
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...COLORS.black);
    pdf.text(heading, MARGIN, y);
    y += 5;
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(...COLORS.slate500);
    pdf.text(subheading, MARGIN, y);
    y += 8;

    // Table header
    const colWidths = [28, 52, 30, CONTENT_WIDTH - 110];
    const colX = [MARGIN, MARGIN + 28, MARGIN + 80, MARGIN + 110];

    checkPage(10);
    pdf.setFillColor(...COLORS.headerBg);
    pdf.rect(MARGIN, y - 3, CONTENT_WIDTH, 7, 'F');
    pdf.setFontSize(7);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...COLORS.slate700);
    pdf.text('Criteria', colX[0] + 2, y);
    pdf.text('Title', colX[1] + 2, y);
    pdf.text('Conformance', colX[2] + 2, y);
    pdf.text('Remarks', colX[3] + 2, y);
    y += 6;

    // Table rows
    for (let i = 0; i < clauses.length; i++) {
      const clause = clauses[i];
      const conformance = toConformanceLevel(clause.status);
      const remarks = buildRemarks(clause);
      const remarksLines = pdf.splitTextToSize(remarks, colWidths[3] - 4);
      const rowHeight = Math.max(remarksLines.length * 3.2 + 2, 5);

      checkPage(rowHeight + 2);

      // Alternate row background
      if (i % 2 === 1) {
        pdf.setFillColor(...COLORS.rowAlt);
        pdf.rect(MARGIN, y - 3, CONTENT_WIDTH, rowHeight + 1, 'F');
      }

      pdf.setFontSize(7);

      // Clause ID
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(...COLORS.slate700);
      pdf.text(clause.clauseId, colX[0] + 2, y);

      // Title (truncated)
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(...COLORS.slate700);
      const vpatTitleSuffix = clause.wcag22Only ? ' (WCAG 2.2)' : '';
      const titleLines = pdf.splitTextToSize(clause.title + vpatTitleSuffix, colWidths[1] - 4);
      pdf.text(titleLines[0], colX[1] + 2, y);

      // Conformance level (colored)
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(...conformanceColor(clause.status));
      pdf.text(conformance, colX[2] + 2, y);

      // Remarks
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(...COLORS.slate500);
      pdf.setFontSize(6.5);
      for (let r = 0; r < Math.min(remarksLines.length, 3); r++) {
        pdf.text(remarksLines[r], colX[3] + 2, y + r * 3.2);
      }

      y += rowHeight;
    }
  }

  if (videoClauses.length > 0) {
    renderTable(
      'Clause 7 — Video & Streaming',
      'EN 301 549 requirements for video content, captions, audio description, and player controls',
      videoClauses,
      [139, 92, 246],
    );
  }

  if (webClauses.length > 0) {
    renderTable(
      'Clause 9 — Web Content (WCAG 2.2 AA)',
      'EN 301 549 requirements mapped to WCAG 2.2 Level A and Level AA success criteria',
      webClauses,
      [6, 182, 212],
    );
  }

  // ─── LEGAL / TEMPLATE INFO ─────────────────────────────────────
  y += 10;
  checkPage(30);

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(...COLORS.black);
  pdf.text('About This Report', MARGIN, y);
  y += 6;

  pdf.setFontSize(7.5);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(...COLORS.slate700);
  const legalText = [
    'This Accessibility Conformance Report (ACR) follows the VPAT\u00AE 2.5 format for the EU edition, covering EN 301 549 V3.2.1 (2021-03) as required by the European Accessibility Act (Directive (EU) 2019/882).',
    'Automated testing was performed using axe-core (WCAG 2.2 AA rules) and custom streaming-specific checks for EN 301 549 Clause 7. Results should be supplemented with manual testing, particularly for criteria marked "Partially Supports."',
    'Conformance levels: "Supports" = functionality meets the criterion; "Partially Supports" = some aspects meet the criterion; "Does Not Support" = functionality does not meet the criterion; "Not Applicable" = criterion is not relevant to the product.',
    'VPAT\u00AE is a registered trademark of the Information Technology Industry Council (ITI). This report was generated automatically and should be reviewed by a qualified accessibility professional before submission.',
  ];

  for (const para of legalText) {
    checkPage(12);
    const lines = pdf.splitTextToSize(para, CONTENT_WIDTH);
    pdf.text(lines, MARGIN, y);
    y += lines.length * 3.2 + 3;
  }

  pdf.save(`vpat-en301549-${new URL(report.url).hostname}-${report.id.slice(0, 8)}.pdf`);
}
